apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ topic_name }}
  namespace: default
spec:
  partitionCount: {{ partitions }}
  replicas: {{ replicas }}
  kafkaRestClassRef:
    name: primary
  configs:
    retention.ms: {{ retention_ms }}
    cleanup.policy: "delete"
